apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app.py
  template:
    metadata:
      labels:
        app: app.py
    spec:
      containers:
      - name: mycontainer1-flask
        image: 153610652855.dkr.ecr.us-east-1.amazonaws.com/flight_status_tracker:latest
        ports:
        - containerPort: 8080
        env:
        - name: API_KEY
          value: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI0IiwianRpIjoiYTc5OWY1MGY1ZDQ3OWFmMDQ5NDI5MGY4ZTMyMGVkOWMxNmRjODBhZDlmY2YyZjgxZTU3MzAxMWNiNDcyOWNiY2ZhYzlkM2MwZDBhNTBjZDkiLCJpYXQiOjE2NzY1Njg5MjQsIm5iZiI6MTY3NjU2ODkyNCwiZXhwIjoxNzA4MTA0OTI0LCJzdWIiOiIxOTk2NyIsInNjb3BlcyI6W119.Y1TnHT9bXvFvaF-4DeRTrqKU-4w8wdpNor5STvy-3dwbqc5DAVQOIzeVMQquMasyMzT3-iv-Ax_-6raQ8LzYUQ